<?php

########################################################################
# Extension Manager/Repository config file for ext: "themes"
#
# Auto generated by Extension Builder 2011-09-08
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Theme Showcase Extension',
	'description' => 'Showcases all the installed Extensions.',
	'category' => 'module',
	'author' => 'themes development team',
	'author_email' => 'kay.strobach@typo3.org',
	'author_company' => 'Kay Strobach',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'themes' => '2.3.1-2.3.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>